### ISSUE TITLE
bundling failed

### ISSUE THREAD

**Issue by dskopa-softdev** [farhan2106/svelte-typescript#2]
Doing this:
```
degit pyoner/svelte-ts-template svelte-ts-app
cd svelte-ts-app
npm install
npm run dev
```

Gives me:
```
rollup v1.10.1
bundles src/main.ts → public\bundle.js...
src/App.svelte:1:2 - error TS2304: Cannot find name 'h1'.

1 <h1>Hello {name}!</h1>
   ~~
src/App.svelte:1:5 - error TS2304: Cannot find name 'Hello'.

1 <h1>Hello {name}!</h1>
      ~~~~~
src/App.svelte:1:11 - error TS1005: ';' expected.

1 <h1>Hello {name}!</h1>
            ~
src/App.svelte:1:12 - error TS2448: Block-scoped variable 'name' used before its declaration.

1 <h1>Hello {name}!</h1>
             ~~~~

  src/App.svelte:17:14
    17   export let name: string;
                    ~~~~
    'name' is declared here.
src/App.svelte:1:12 - error TS2454: Variable 'name' is used before being assigned.

1 <h1>Hello {name}!</h1>
             ~~~~
src/App.svelte:1:19 - error TS1110: Type expected.

1 <h1>Hello {name}!</h1>
                    ~
src/App.svelte:1:20 - error TS1161: Unterminated regular expression literal.

1 <h1>Hello {name}!</h1>

src/App.svelte:2:2 - error TS2304: Cannot find name 'p'.

2 <p>
   ~
src/App.svelte:3:12 - error TS1005: '>' expected.

3   <Counter />
             ~
src/App.svelte:3:13 - error TS1161: Unterminated regular expression literal.

3   <Counter />

src/App.svelte:4:12 - error TS1005: ';' expected.

4   <Counter value={1}>Counter 1</Counter>
             ~~~~~
src/App.svelte:4:12 - error TS2304: Cannot find name 'value'.

4   <Counter value={1}>Counter 1</Counter>
             ~~~~~
src/App.svelte:4:20 - error TS1005: ':' expected.

4   <Counter value={1}>Counter 1</Counter>
                     ~
src/App.svelte:4:30 - error TS1005: ';' expected.

4   <Counter value={1}>Counter 1</Counter>
                               ~
src/App.svelte:4:30 - error TS2365: Operator '<' cannot be applied to types 'number' and 'RegExp'.

4   <Counter value={1}>Counter 1</Counter>
                               ~~~~~~~~~~~
src/App.svelte:4:33 - error TS1161: Unterminated regular expression literal.

4   <Counter value={1}>Counter 1</Counter>

src/App.svelte:5:12 - error TS1005: ';' expected.

5   <Counter value={100} step={3}>Counter 2</Counter>
             ~~~~~
src/App.svelte:5:12 - error TS2304: Cannot find name 'value'.

5   <Counter value={100} step={3}>Counter 2</Counter>
             ~~~~~
src/App.svelte:5:22 - error TS1005: ':' expected.

5   <Counter value={100} step={3}>Counter 2</Counter>
                       ~
src/App.svelte:5:24 - error TS1005: ';' expected.

5   <Counter value={100} step={3}>Counter 2</Counter>
                         ~~~~
src/App.svelte:5:24 - error TS2304: Cannot find name 'step'.

5   <Counter value={100} step={3}>Counter 2</Counter>
                         ~~~~
src/App.svelte:5:31 - error TS1005: ':' expected.

5   <Counter value={100} step={3}>Counter 2</Counter>
                                ~
src/App.svelte:5:41 - error TS1005: ';' expected.

5   <Counter value={100} step={3}>Counter 2</Counter>
                                          ~
src/App.svelte:5:41 - error TS2365: Operator '<' cannot be applied to types 'number' and 'RegExp'.

5   <Counter value={100} step={3}>Counter 2</Counter>
                                          ~~~~~~~~~~~
src/App.svelte:5:41 - error TS2365: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.

5   <Counter value={100} step={3}>Counter 2</Counter>
                                          ~~~~~~~~~~~
6 </p>
  ~~~~
src/App.svelte:5:44 - error TS1161: Unterminated regular expression literal.

5   <Counter value={100} step={3}>Counter 2</Counter>

src/App.svelte:6:3 - error TS1161: Unterminated regular expression literal.

6 </p>

src/App.svelte:8:2 - error TS2304: Cannot find name 'style'.

8 <style>
   ~~~~~
src/App.svelte:9:3 - error TS2304: Cannot find name 'h1'.

9   h1 {
    ~~
src/App.svelte:9:6 - error TS1005: ';' expected.

9   h1 {
       ~
src/App.svelte:10:12 - error TS2304: Cannot find name 'purple'.

10     color: purple;
              ~~~~~~
src/App.svelte:12:2 - error TS1110: Type expected.

12 </style>
    ~
src/App.svelte:12:3 - error TS1161: Unterminated regular expression literal.

12 </style>

src/App.svelte:14:2 - error TS2552: Cannot find name 'script'. Did you mean 'WScript'?

14 <script lang="ts">
    ~~~~~~

  node_modules/typescript/lib/lib.scripthost.d.ts:120:13
    120 declare var WScript: {
                    ~~~~~~~
    'WScript' is declared here.
src/App.svelte:14:9 - error TS1005: ';' expected.

14 <script lang="ts">
           ~~~~
src/App.svelte:14:9 - error TS2304: Cannot find name 'lang'.

14 <script lang="ts">
           ~~~~
src/App.svelte:15:3 - error TS1109: Expression expected.

15   import Counter from "./Counter.svelte";
     ~~~~~~
src/App.svelte:18:2 - error TS1110: Type expected.

18 </script>
    ~
src/App.svelte:18:3 - error TS1161: Unterminated regular expression literal.

18 </script>


[!] (svelte plugin) ParseError: Unterminated regular expression
src\App.svelte
16:     name;
17: }
18: !/h1>
      ^
19:     < p >
20:     />
ParseError: Unterminated regular expression
    at error$1 (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:13421:20)
    at Parser$2.error (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:13497:10)
    at Parser$2.acorn_error (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:13491:15)
    at Object.read_script [as read] (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:5263:17)
    at tag (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:12626:34)
    at new Parser$2 (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:13456:22)
    at parse$2 (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:13587:21)
    at compile (H:\Dev\svelte-ts-app\node_modules\svelte\compiler.js:23611:12)
    at preprocessPromise.then.code (H:\Dev\svelte-ts-app\node_modules\rollup-plugin-svelte\index.js:236:22)

1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-ts-app@1.0.0 autobuild: `rollup -c -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-ts-app@1.0.0 autobuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dskopa\AppData\Roaming\npm-cache\_logs\2019-04-29T14_59_44_504Z-debug.log
ERROR: "autobuild" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-ts-app@1.0.0 dev: `run-p start:dev autobuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-ts-app@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dskopa\AppData\Roaming\npm-cache\_logs\2019-04-29T14_59_44_732Z-debug.log
```

**Comment by farhan2106** [comment]
Correct me if I am wrong, I think you are in the wrong repo?

Aren't you using this repository? https://github.com/PaulMaly/svelte-ts-preprocess

**Comment by dskopa-softdev** [comment]
oh my... i'm sorry :)
